PD: Reset phy state when ignoring a packet
goToMain/libosdp pull request #101
Opened 2022-12-15 00:14 UTC by bjyoungblood

When receiving a non-multicast packet addressed to another PD, the PD kept trying to process it indefinitely instead of moving on to the next packet in the RX ring buffer.

2023-01-03 00:23 UTC, sidcha requested changes

2023-01-03 00:23 UTC, sidcha commented on src/osdp_pd.c
> +		osdp_phy_state_reset(pd, false);
We cannot reset phy state for `OSDP_PD_ERR_NO_DATA`. Instead, this has to be moved to `pd_receive_and_process_command()` under `case OSDP_ERR_PKT_SKIP:`.

2023-01-06 20:00 UTC, bjyoungblood commented
Thanks for the review! I have updated as you suggested.

2023-01-06 23:10 UTC, sidcha approved these changes

2023-01-06 23:10 UTC, merged