Add support for additional baud rate 57600
goToMain/libosdp pull request #119
Opened 2023-06-06 08:25 UTC by sgouraud

According specification, half-duplex asynchronous serial should support at least one of 9600, 19200, 38400, 57600, 115200, 230400 Baud. Adding support for 57600.

2023-06-13 20:00 UTC, sidcha requested changes
Minor nit, otherwise LGTM.

2023-06-13 20:00 UTC, sidcha commented on osdpctl/cmd_send.c
> +		baud != 115200 && baud != 230400)
The coding style we follow requires the multi-line `if` conditions to align to the next char after the opening bracket '('. So the hunk above becomes:

```suggestion
	if (baud != 9600 && baud != 19200 && baud != 38400 && baud != 57600 && 
	    baud != 115200 && baud != 230400)
```

(Same change to the other hunk as well)

2023-06-14 06:56 UTC, sgouraud commented on osdpctl/cmd_send.c
> +		baud != 115200 && baud != 230400)
OK, sorry. Tabs in my IDE is 4 spaces equivalent, I didn't notice it ^^. PR updated according your review. Thanks for your great job :)

2023-06-14 09:04 UTC, sidcha approved these changes

2023-06-14 09:04 UTC, merged